baseurl = "/"
languageCode = "en-us"
title = "Adam Shelton"
theme = "github-dev-page"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/tonofshell"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/tonofshell"

[params]
    description = "A social data scientist"
    
    github = "https://github.com/tonofshell"
    linkedin = "http://linkedin.com/in/tonofshell"
    contact = "http://m.me/tonofshell"
    

    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "images/favicon.ico"

[params.logo]
    url = "me.jpg"
    width = "100%"
    height = "100%"
    alt = "Logo"

