name = "Github Developer Page"
license = "MIT"
licenselink = "https://github.com/tonofshell/github-dev-page/"
description = "An blog-like single-page website for showing yourself off."
homepage = "https://github.com/tonofshell/github-dev-page/"
tags = ["company", "job", "landing page", "advertising", "opensource"]
features = ["github", "images" ]
min_version= 0.1

[author]
     name = "Adam Shelton"

[original]
    author =  "Adam Shelton"
    homepage = "https://github.com/tonofshell/github-dev-page/"
    repo = "https://github.com/tonofshell/github-dev-page/"
